# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-01-21 09:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='lesson',
            field=models.IntegerField(choices=[(1, b'\xe5\x9f\xba\xe7\xa4\x8e\xe7\xa8\x8b\xe5\xbc\x8f\xe8\xa8\xad\xe8\xa8\x88'), (2, b'\xe9\x80\xb2\xe9\x9a\x8e\xe7\xa8\x8b\xe5\xbc\x8f\xe8\xa8\xad\xe8\xa8\x88')], default=1),
        ),
    ]
