# -*- coding: UTF-8 -*-
lesson_list = []

def reset():
    lesson_list.append(['基礎程式設計：使用Scratch', []])
    lesson_list[0][1].append(['基礎篇', []])
    lesson_list[0][1][0][1].append(['例：貓狗對話', False])
    lesson_list[0][1][0][1].append(['練：勇者鬥惡龍', False])    
    lesson_list[0][1].append(['繪圖篇', []])
    lesson_list[0][1][1][1].append(['例：畫方形', False])    
    lesson_list[0][1][1][1].append(['練：畫星星', False])    
    lesson_list[0][1][1][1].append(['例：擴散方形', False])     
    lesson_list[0][1][1][1].append(['例：旋轉方形', False])    
    lesson_list[0][1][1][1].append(['例：平行方形', False])    
    lesson_list[0][1][1][1].append(['練：放大方形', False])        
    lesson_list[0][1].append(['遊戲篇', []])
    lesson_list[0][1][2][1].append(['例：打雷', True])    
    lesson_list[0][1][2][1].append(['例：打擊魔鬼', True])    
    lesson_list[0][1][2][1].append(['例：星際大戰', True])           
    lesson_list[0][1].append(['計算篇', []])
    lesson_list[0][1][3][1].append(['例：求平均數', False])    
    lesson_list[0][1][3][1].append(['練：溫度換算', False])    
    lesson_list[0][1][3][1].append(['例：成績計算', False])     
    lesson_list[0][1][3][1].append(['練：書店打折', False])    
    lesson_list[0][1][3][1].append(['例：累加計算', False])    
    lesson_list[0][1][3][1].append(['練：累乘計算', False])  
    lesson_list[0][1][3][1].append(['例：密碼檢查', False])      
    lesson_list[0][1].append(['模擬篇', []])
    lesson_list[0][1][4][1].append(['例：電子琴', True])  
    lesson_list[0][1][4][1].append(['例：電梯', True] )      
reset()