# -*- coding: UTF-8 -*-
lesson_list = []

def reset():
    lesson_list.append(['基礎程式設計：使用Scratch', []])
    lesson_list[0][1].append(['基礎篇', []])
    lesson_list[0][1][0][1].append('例：貓狗對話')
    lesson_list[0][1][0][1].append('練：勇者鬥惡龍')    
    lesson_list[0][1].append(['繪圖篇', []])
    lesson_list[0][1][1][1].append('例：畫方形')    
    lesson_list[0][1][1][1].append('練：畫星星')    
    lesson_list[0][1][1][1].append('例：擴散方形')     
    lesson_list[0][1][1][1].append('例：旋轉方形')    
    lesson_list[0][1][1][1].append('例：平行方形')    
    lesson_list[0][1][1][1].append('練：放大方形')        
    lesson_list[0][1].append(['遊戲篇', []])
    lesson_list[0][1][2][1].append('例：打雷')    
    lesson_list[0][1][2][1].append('例：打擊魔鬼')    
    lesson_list[0][1][2][1].append('例：星際大戰')           
    lesson_list[0][1].append(['計算篇', []])
    lesson_list[0][1][3][1].append('例：求平均數')    
    lesson_list[0][1][3][1].append('練：溫度換算')    
    lesson_list[0][1][3][1].append('例：成績計算')     
    lesson_list[0][1][3][1].append('練：書店打折')    
    lesson_list[0][1][3][1].append('例：累加計算')    
    lesson_list[0][1][3][1].append('練：累乘計算')  
    lesson_list[0][1][3][1].append('例：密碼檢查')      
    lesson_list[0][1].append(['模擬篇', []])
    lesson_list[0][1][4][1].append('例：電子琴')  
    lesson_list[0][1][4][1].append('例：電梯')      
reset()