# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-01-21 11:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_importuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImportUser',
        ),
    ]
