# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-01-22 20:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_delete_importuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='lesson',
            field=models.IntegerField(default=0),
        ),
    ]
